# -*- coding: utf-8 -*-
import json
import os

def translate_notebook(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        notebook = json.load(f)

    translations = {
        "Supplementary code for the <a href=\"http://mng.bz/orYv\">Build a Large Language Model From Scratch</a> book by <a href=\"https://sebastianraschka.com\">Sebastian Raschka</a><br>\n": "《<a href=\"http://mng.bz/orYv\">从头开始构建大型语言模型</a>》一书的补充代码，作者 <a href=\"https://sebastianraschka.com\">Sebastian Raschka</a><br>\n",
        "<br>Code repository: <a href=\"https://github.com/rasbt/LLMs-from-scratch\">https://github.com/rasbt/LLMs-from-scratch</a>\n": "<br>代码仓库：<a href=\"https://github.com/rasbt/LLMs-from-scratch\">https://github.com/rasbt/LLMs-from-scratch</a>\n",
        "# Chapter 7: Finetuning To Follow Instructions": "# 第 7 章：微调以遵循指令",
        "## 7.1 Introduction to instruction finetuning": "## 7.1 指令微调简介",
        "- In chapter 5, we saw that pretraining an LLM involves a training procedure where it learns to generate one word at a time\n": "- 在第 5 章中，我们看到预训练 LLM 涉及一个训练过程，在这个过程中它学习一次生成一个词\n",
        "- Hence, a pretrained LLM is good at text completion, but it is not good at following instructions\n": "- 因此，预训练的 LLM 擅长文本补全，但不擅长遵循指令\n",
        "- In this chapter, we teach the LLM to follow instructions better": "- 在本章中，我们将教 LLM 更好地遵循指令",
        "- The topics covered in this chapter are summarized in the figure below\n": "- 本章涵盖的主题总结在下图中\n",
        "## 7.2 Preparing a dataset for supervised instruction finetuning": "## 7.2 准备用于监督指令微调的数据集",
        "- We will work with an instruction dataset I prepared for this chapter": "- 我们将使用我为本章准备的指令数据集",
        "- Each item in the `data` list we loaded from the JSON file above is a dictionary in the following form": "- 我们从上面的 JSON 文件加载的 `data` 列表中的每一项都是以下形式的字典",
        "- Note that the `'input'` field can be empty:": "- 请注意，`'input'` 字段可以为空：",
        "- Instruction finetuning is often referred to as \"supervised instruction finetuning\" because it involves training a model on a dataset where the input-output pairs are explicitly provided\n": "- 指令微调通常被称为“监督指令微调”，因为它涉及在显式提供输入-输出对的数据集上训练模型\n",
        "- There are different ways to format the entries as inputs to the LLM; the figure below illustrates two example formats that were used for training the Alpaca (https://crfm.stanford.edu/2023/03/13/alpaca.html) and Phi-3 (https://arxiv.org/abs/2404.14219) LLMs, respectively": "- 有多种方法可以将条目格式化为 LLM 的输入；下图说明了分别用于训练 Alpaca (https://crfm.stanford.edu/2023/03/13/alpaca.html) 和 Phi-3 (https://arxiv.org/abs/2404.14219) LLM 的两种示例格式",
        "- In this chapter, we use Alpaca-style prompt formatting, which was the original prompt template for instruction finetuning\n": "- 在本章中，我们使用 Alpaca 风格的提示格式，这是指令微调的原始提示模板\n",
        "- Below, we format the input that we will pass as input to the LLM": "- 下面，我们格式化将作为输入传递给 LLM 的输入",
        "- A formatted response with input field looks like as shown below": "- 带有输入字段的格式化响应如下所示",
        "- Below is a formatted response without an input field": "- 下面是没有输入字段的格式化响应",
        "- Lastly, before we prepare the PyTorch data loaders in the next section, we divide the dataset into a training, validation, and test set": "- 最后，在下一节准备 PyTorch 数据加载器之前，我们将数据集分为训练集、验证集和测试集",
        "## 7.3 Organizing data into training batches": "## 7.3 将数据组织成训练批次",
        "- We tackle this dataset batching in several steps, as summarized in the figure below\n": "- 我们分几个步骤处理此数据集批处理，如下图所示\n",
        "- First, we implement an `InstructionDataset` class that pre-tokenizes all inputs in the dataset, similar to the `SpamDataset` in chapter 6\n": "- 首先，我们要实现一个 `InstructionDataset` 类，它会对数据集中的所有输入进行预分词，类似于第 6 章中的 `SpamDataset`\n",
        "- Similar to chapter 6, we want to collect multiple training examples in a batch to accelerate training; this requires padding all inputs to a similar length\n": "- 与第 6 章类似，我们希望在一个批次中收集多个训练示例以加速训练；这需要将所有输入填充到相似的长度\n",
        "- Also similar to the previous chapter, we use the `<|endoftext|>` token as a padding token": "- 同样类似于前一章，我们使用 `<|endoftext|>` 标记作为填充标记",
        "- In chapter 6, we padded all examples in a dataset to the same length\n": "- 在第 6 章中，我们将数据集中的所有示例填充到相同的长度\n",
        "  - Here, we take a more sophisticated approach and develop a custom \"collate\" function that we can pass to the data loader\n": "  - 在这里，我们采用更复杂的方法，并开发一个自定义的“collate”函数，我们可以将其传递给数据加载器\n",
        "  - This custom collate function pads the training examples in each batch to have the same length (but different batches can have different lengths)": "  - 这个自定义 collate 函数将每个批次中的训练示例填充为具有相同的长度（但不同的批次可以具有不同的长度）",
        "- Above, we only returned the inputs to the LLM; however, for LLM training, we also need the target values\n": "- 上面，我们只返回了 LLM 的输入；然而，对于 LLM 训练，我们还需要目标值\n",
        "- Similar to pretraining an LLM, the targets are the inputs shifted by 1 position to the right, so the LLM learns to predict the next token": "- 与预训练 LLM 类似，目标是向右移动 1 个位置的输入，因此 LLM 学习预测下一个标记",
        "- Next, we introduce an `ignore_index` value to replace all padding token IDs with a new value; the purpose of this `ignore_index` is that we can ignore padding values in the loss function (more on that later)\n": "- 接下来，我们引入一个 `ignore_index` 值，用新值替换所有填充标记 ID；这个 `ignore_index` 的目的是我们可以在损失函数中忽略填充值（稍后会详细介绍）\n",
        "- Concretely, this means that we replace the token IDs corresponding to `50256` with `-100` as illustrated below": "- 具体来说，这意味着我们将对应于 `50256` 的标记 ID 替换为 `-100`，如下图所示",
        "- (In addition, we also introduce the `allowed_max_length` in case we want to limit the length of the samples; this will be useful if you plan to work with your own datasets that are longer than the 1024 token context size supported by the GPT-2 model)": "- （此外，我们还引入了 `allowed_max_length`，以防我们想要限制样本的长度；如果您计划使用比 GPT-2 模型支持的 1024 标记上下文大小更长的自己的数据集，这将非常有用）",
        "- Let's see what this replacement by -100 accomplishes\n": "- 让我们看看用 -100 替换能实现什么\n",
        "- For illustration purposes, let's assume we have a small classification task with 2 class labels, 0 and 1, similar to chapter 6\n": "- 为了说明起见，让我们假设我们有一个带有 2 个类标签 0 和 1 的小型分类任务，类似于第 6 章\n",
        "- If we have the following logits values (outputs of the last layer of the model), we calculate the following loss": "- 如果我们要有以下 logits 值（模型最后一层的输出），我们要计算以下损失",
        "- Now, adding one more training example will, as expected, influence the loss": "- 现在，添加另外一个训练示例将如预期的那样影响损失",
        "- Let's see what happens if we replace the class label of one of the examples with -100": "- 让我们看看如果我们将其中一个示例的类标签替换为 -100 会发生什么",
        "- As we can see, the resulting loss on these 3 training examples is the same as the loss we calculated from the 2 training examples, which means that the cross-entropy loss function ignored the training example with the -100 label\n": "- 我们可以看到，这 3 个训练示例的最终损失与我们从 2 个训练示例计算的损失相同，这意味着交叉熵损失函数忽略了带有 -100 标签的训练示例\n",
        "- By default, PyTorch has the `cross_entropy(..., ignore_index=-100)` setting to ignore examples corresponding to the label -100\n": "- 默认情况下，PyTorch 具有 `cross_entropy(..., ignore_index=-100)` 设置，以忽略对应于标签 -100 的示例\n",
        "- Using this -100 `ignore_index`, we can ignore the additional end-of-text (padding) tokens in the batches that we used to pad the training examples to equal length\n": "- 使用这个 -100 `ignore_index`，我们可以忽略我们在批次中用于将训练示例填充到相同长度的额外文本结束（填充）标记\n",
        "- However, we don't want to ignore the first instance of the end-of-text (padding) token (50256) because it can help signal to the LLM when the response is complete": "- 但是，我们不想忽略文本结束（填充）标记 (50256) 的第一个实例，因为它可以帮助向 LLM 发出响应完成的信号",
        "- In practice, it is also common to mask out the target token IDs that correspond to the instruction, as illustrated in the figure below (this is a recommended reader exercise after completing the chapter)": "- 在实践中，通常还会屏蔽对应于指令的目标标记 ID，如下图所示（这是完成本章后的推荐读者练习）",
        "## 7.4 Creating data loaders for an instruction dataset": "## 7.4 为指令数据集创建数据加载器",
        "- In this section, we use the `InstructionDataset` class and `custom_collate_fn` function to instantiate the training, validation, and test data loaders": "- 在本节中，我们将使用 `InstructionDataset` 类和 `custom_collate_fn` 函数来实例化训练、验证和测试数据加载器",
        "- Another additional detail of the previous `custom_collate_fn` function is that we now directly move the data to the target device (e.g., GPU) instead of doing it in the main training loop, which improves efficiency because it can be carried out as a background process when we use the `custom_collate_fn` as part of the data loader\n": "- 之前 `custom_collate_fn` 函数的另一个额外细节是，我们现在直接将数据移动到目标设备（例如 GPU），而不是在主训练循环中进行，这提高了效率，因为当我们使用 `custom_collate_fn` 作为数据加载器的一部分时，它可以作为后台进程执行\n",
        "- Using the `partial` function from Python's `functools` standard library, we create a new function with the `device` argument of the original function pre-filled": "- 使用 Python `functools` 标准库中的 `partial` 函数，我们创建了一个新函数，其中预填充了原始函数的 `device` 参数",
        "- Next, we instantiate the data loaders similar to previous chapters, except that we now provide our own collate function for the batching process": "- 接下来，我们实例化数据加载器，类似于前面的章节，只是我们现在为批处理过程提供了我们自己的 collate 函数",
        "- Let's see what the dimensions of the resulting input and target batches look like": "- 让我们看看生成的输入和目标批次的维度是什么样的",
        "- As we can see based on the output above, all batches have a batch size of 8 but a different length, as expected\n": "- 正如我们根据上面的输出所看到的，所有批次的批大小都为 8，但长度不同，正如预期的那样\n",
        "- Let's also double-check that the inputs contain the `<|endoftext|>` padding tokens corresponding to token ID 50256 by printing the contents of the first training example in the `inputs` batch": "- 让我们通过打印 `inputs` 批次中第一个训练示例的内容，再次检查输入是否包含对应于标记 ID 50256 的 `<|endoftext|>` 填充标记",
        "- Similarly, we visually double-check that the targets contain the -100 placeholder tokens": "- 同样，我们在视觉上再次检查目标是否包含 -100 占位符标记",
        "## 7.5 Loading a pretrained LLM": "## 7.5 加载预训练的 LLM",
        "- In this section, we load a pretrained GPT model using the same code that we used in section 5.5 of chapter 5 and section 6.4 in chapter 6": "- 在本节中，我们将使用我们在第 5 章第 5.5 节和第 6 章第 6.4 节中使用的相同代码加载预训练的 GPT 模型",
        "- However, instead of loading the smallest 124 million parameter model, we load the medium version with 355 million parameters since the 124 million model is too small for achieving qualitatively reasonable results via instruction finetuning": "- 但是，我们不再加载最小的 1.24 亿参数模型，而是加载具有 3.55 亿参数的中型版本，因为 1.24 亿模型太小，无法通过指令微调获得定性合理的结果",
        "- Before we start finetuning the model in the next section, let's see how it performs on one of the validation tasks": "- 在下一节开始微调模型之前，让我们看看它在其中一个验证任务上的表现",
        "- Note that the `generate` function we used in previous chapters returns the combined input and output text, which was convenient in the previous section for creating legible text\n": "- 请注意，我们在前几章中使用的 `generate` 函数返回组合的输入和输出文本，这在上一节中对于创建清晰的文本很方便\n",
        "- To isolate the response, we can subtract the length of the instruction from the start of the `generated_text`": "- 为了隔离响应，我们可以从 `generated_text` 的开头减去指令的长度",
        "- As we can see, the model is not capable of following the instructions, yet; it creates a \"Response\" section but it simply repeats the original input sentence as well as the instruction": "- 我们可以看到，该模型目前还无法遵循指令；它创建了一个“Response”部分，但它只是重复了原始输入句子以及指令",
        "## 7.6 Finetuning the LLM on instruction data": "## 7.6 在指令数据上微调 LLM",
        "- In this section, we finetune the model\n": "- 在本节中，我们将微调模型\n",
        "- Note that we can reuse all the loss calculation and training functions that we used in previous chapters": "- 请注意，我们可以重用我们在前几章中使用的所有损失计算和训练函数",
        "- Let's calculate the initial training and validation set loss before we start training (as in previous chapters, the goal is to minimize the loss)": "- 让我们在开始训练之前计算初始训练和验证集损失（与前几章一样，目标是最小化损失）",
        "- Note that the training is a bit more expensive than in previous chapters since we are using a larger model (355 million instead of 124 million parameters)\n": "- 请注意，训练比前几章稍微昂贵一些，因为我们使用的是更大的模型（3.55 亿而不是 1.24 亿参数）\n",
        "- The runtimes for various devices are shown for reference below (running this notebook on a compatible GPU device requires no changes to the code)": "- 各种设备的运行时间如下所示，以供参考（在兼容的 GPU 设备上运行此笔记本无需更改代码）",
        "- I ran this notebook using the `\"gpt2-medium (355M)\"` model": "- 我使用 `\"gpt2-medium (355M)\"` 模型运行了这个笔记本",
        "- As we can see based on the outputs above, the model trains well, as we can tell based on the decreasing training loss and validation loss values\n": "- 正如我们根据上面的输出所看到的，模型训练得很好，我们可以根据不断下降的训练损失和验证损失值来判断\n",
        "- Furthermore, based on the response text printed after each epoch, we can see that the model correctly follows the instruction to convert the input sentence `'The chef cooks the meal every day.'` into passive voice `'The meal is cooked every day by the chef.'` (We will properly format and evaluate the responses in a later section)\n": "- 此外，根据每个 epoch 后打印的响应文本，我们可以看到模型正确地遵循了将输入句子 `'The chef cooks the meal every day.'` 转换为被动语态 `'The meal is cooked every day by the chef.'` 的指令（我们将在后面的部分正确格式化和评估响应）\n",
        "- Finally, let's take a look at the training and validation loss curves": "- 最后，让我们看看训练和验证损失曲线",
        "- As we can see, the loss decreases sharply at the beginning of the first epoch, which means the model starts learning quickly\n": "- 我们可以看到，损失在第一个 epoch 开始时急剧下降，这意味着模型开始快速学习\n",
        "- We can see that slight overfitting sets in at around 1 training epoch": "- 我们可以看到，在大约 1 个训练 epoch 时出现了轻微的过拟合",
        "## 7.7 Extracting and saving responses": "## 7.7 提取并保存响应",
        "- In this section, we save the test set responses for scoring in the next section\n": "- 在本节中，我们将保存测试集响应以便在下一节中进行评分\n",
        "- We also save a copy of the model for future use\n": "- 我们还保存了一份模型副本以备将来使用\n",
        "- But first, let's take a brief look at the responses generated by the finetuned model": "- 但首先，让我们简要看一下微调后的模型生成的响应",
        "- As we can see based on the test set instructions, given responses, and the model's responses, the model performs relatively well\n": "- 我们可以看到，根据测试集指令、给定的响应和模型的响应，该模型的表现相对较好\n",
        "- The answers to the first and last instructions are clearly correct\n": "- 第一条和最后一条指令的答案显然是正确的\n",
        "- The second answer is close; the model answers with \"cumulus cloud\" instead of \"cumulonimbus\" (however, note that cumulus clouds can develop into cumulonimbus clouds, which are capable of producing thunderstorms)\n": "- 第二个答案很接近；模型回答的是“积云 (cumulus cloud)”，而不是“积雨云 (cumulonimbus)”（不过，请注意，积云可以发展成能够产生雷暴的积雨云）\n",
        "- Most importantly, we can see that model evaluation is not as straightforward as in the previous chapter, where we just had to calculate the percentage of correct spam/non-spam class labels to obtain the classification accuracy\n": "- 最重要的是，我们可以看到模型评估并不像前一章那样简单，在前一章中，我们只需要计算正确的垃圾邮件/非垃圾邮件类标签的百分比即可获得分类准确率\n",
        "- In practice, instruction-finetuned LLMs such as chatbots are evaluated via multiple approaches\n": "- 在实践中，指令微调的 LLM（例如聊天机器人）通过多种方法进行评估\n",
        "  - short-answer and multiple choice benchmarks such as MMLU (\"Measuring Massive Multitask Language Understanding\", [https://arxiv.org/abs/2009.03300](https://arxiv.org/abs/2009.03300)), which test the knowledge of a model\n": "  - 简答和多项选择基准，例如 MMLU（“测量大规模多任务语言理解”，[https://arxiv.org/abs/2009.03300](https://arxiv.org/abs/2009.03300)），用于测试模型的知识\n",
        "  - human preference comparison to other LLMs, such as LMSYS chatbot arena ([https://arena.lmsys.org](https://arena.lmsys.org))\n": "  - 与其他 LLM 的人类偏好比较，例如 LMSYS 聊天机器人竞技场 ([https://arena.lmsys.org](https://arena.lmsys.org))\n",
        "  - automated conversational benchmarks, where another LLM like GPT-4 is used to evaluate the responses, such as AlpacaEval ([https://tatsu-lab.github.io/alpaca_eval/](https://tatsu-lab.github.io/alpaca_eval/))\n": "  - 自动对话基准，其中使用另一个 LLM（如 GPT-4）来评估响应，例如 AlpacaEval ([https://tatsu-lab.github.io/alpaca_eval/](https://tatsu-lab.github.io/alpaca_eval/))\n",
        "- In the next section, we will use an approach similar to AlpacaEval and use another LLM to evaluate the responses of our model; however, we will use our own test set instead of using a publicly available benchmark dataset\n": "- 在下一节中，我们将使用类似于 AlpacaEval 的方法，并使用另一个 LLM 来评估我们模型的响应；但是，我们将使用我们自己的测试集，而不是使用公开可用的基准数据集\n",
        "- For this, we add the model response to the `test_data` dictionary and save it as a `\"instruction-data-with-response.json\"` file for record-keeping so that we can load and analyze it in separate Python sessions if needed": "- 为此，我们将模型响应添加到 `test_data` 字典中，并将其保存为 `\"instruction-data-with-response.json\"` 文件以进行记录，以便我们可以在需要时在单独的 Python 会话中加载和分析它",
        "- Let's double-check one of the entries to see whether the responses have been added to the `test_data` dictionary correctly": "- 让我们再次检查其中一个条目，看看响应是否已正确添加到 `test_data` 字典中",
        "- Finally, we also save the model in case we want to reuse it in the future": "- 最后，我们还保存模型，以防我们将来想重用它",
        "## 7.8 Evaluating the finetuned LLM": "## 7.8 评估微调后的 LLM",
        "- In this section, we automate the response evaluation of the finetuned LLM using another, larger LLM\n": "- 在本节中，我们使用另一个更大的 LLM 自动化微调后 LLM 的响应评估\n",
        "- In particular, we use an instruction-finetuned 8-billion-parameter Llama 3 model by Meta AI that can be run locally via ollama ([https://ollama.com](https://ollama.com))\n": "- 特别是，我们使用了 Meta AI 的指令微调的 80 亿参数 Llama 3 模型，该模型可以通过 ollama ([https://ollama.com](https://ollama.com)) 在本地运行\n",
        "- (Alternatively, if you prefer using a more capable LLM like GPT-4 via the OpenAI API, please see the [llm-instruction-eval-openai.ipynb](../03_model-evaluation/llm-instruction-eval-openai.ipynb) notebook)": "- （或者，如果您更喜欢通过 OpenAI API 使用功能更强大的 LLM（如 GPT-4），请参阅 [llm-instruction-eval-openai.ipynb](../03_model-evaluation/llm-instruction-eval-openai.ipynb) 笔记本）",
        "- Ollama is an application to run LLMs efficiently\n": "- Ollama 是一个高效运行 LLM 的应用程序\n",
        "- It is a wrapper around llama.cpp ([https://github.com/ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp)), which implements LLMs in pure C/C++ to maximize efficiency\n": "- 它是 llama.cpp ([https://github.com/ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp)) 的包装器，它用纯 C/C++ 实现 LLM 以最大限度地提高效率\n",
        "- Note that it is a tool for using LLMs to generate text (inference), not training or finetuning LLMs\n": "- 请注意，它是用于使用 LLM 生成文本（推理）的工具，而不是训练或微调 LLM\n",
        "- Before running the code below, install ollama by visiting [https://ollama.com](https://ollama.com) and following the instructions (for instance, clicking on the \"Download\" button and downloading the ollama application for your operating system)": "- 在运行下面的代码之前，请通过访问 [https://ollama.com](https://ollama.com) 并按照说明安装 ollama（例如，单击“下载”按钮并下载适用于您的操作系统的 ollama 应用程序）",
        "- For macOS and Windows users, click on the ollama application you downloaded; if it prompts you to install the command line usage, say \"yes\"\n": "- 对于 macOS 和 Windows 用户，单击您下载的 ollama 应用程序；如果它提示您安装命令行用法，请说“是”\n",
        "- Linux users can use the installation command provided on the ollama website\n": "- Linux 用户可以使用 ollama 网站上提供的安装命令\n",
        "- In general, before we can use ollama from the command line, we have to either start the ollama application or run `ollama serve` in a separate terminal\n": "- 通常，在我们从命令行使用 ollama 之前，我们要么启动 ollama 应用程序，要么在单独的终端中运行 `ollama serve`\n",
        "- When running `ollama serve` in the terminal, as described above, you may encounter an error message saying `Error: listen tcp 127.0.0.1:11434: bind: address already in use`\n": "- 如上所述，在终端中运行 `ollama serve` 时，您可能会遇到一条错误消息，提示 `Error: listen tcp 127.0.0.1:11434: bind: address already in use`\n",
        "- If that's the case, try use the command `OLLAMA_HOST=127.0.0.1:11435 ollama serve` (and if this address is also in use, try to increment the numbers by one until you find an address not in use\n": "- 如果是这种情况，请尝试使用命令 `OLLAMA_HOST=127.0.0.1:11435 ollama serve`（如果此地址也被占用，请尝试将数字加一，直到找到未使用的地址\n",
        "- With the ollama application or `ollama serve` running in a different terminal, on the command line, execute the following command to try out the 8-billion-parameter Llama 3 model (the model, which takes up 4.7 GB of storage space, will be automatically downloaded the first time you execute this command)\n": "- 在不同的终端中运行 ollama 应用程序或 `ollama serve`，在命令行上执行以下命令以试用 80 亿参数的 Llama 3 模型（该模型占用 4.7 GB 的存储空间，将在您首次执行此命令时自动下载）\n",
        "The output looks like as follows\n": "输出如下所示\n",
        "- Note that `llama3` refers to the instruction finetuned 8-billion-parameter Llama 3 model\n": "- 请注意，`llama3` 指的是指令微调的 80 亿参数 Llama 3 模型\n",
        "- Using ollama with the `\"llama3\"` model (a 8B parameter model) requires 16 GB of RAM; if this is not supported by your machine, you can try the smaller model, such as the 3.8B parameter phi-3 model by setting `model = \"phi-3\"`, which only requires 8 GB of RAM\n": "- 使用带有 `\"llama3\"` 模型（80 亿参数模型）的 ollama 需要 16 GB 的 RAM；如果您的机器不支持此功能，您可以尝试较小的模型，例如通过设置 `model = \"phi-3\"` 使用 38 亿参数的 phi-3 模型，它只需要 8 GB 的 RAM\n",
        "- Alternatively, you can also use the larger 70-billion-parameter Llama 3 model, if your machine supports it, by replacing `llama3` with `llama3:70b`\n": "- 或者，如果您的机器支持，您也可以使用更大的 700 亿参数 Llama 3 模型，方法是将 `llama3` 替换为 `llama3:70b`\n",
        "- After the download has been completed, you will see a command line prompt that allows you to chat with the model\n": "- 下载完成后，您将看到一个命令行提示符，允许您与模型聊天\n",
        "- Try a prompt like \"What do llamas eat?\", which should return an output similar to the following\n": "- 尝试诸如“What do llamas eat?”之类的提示，它应该返回类似于以下的输出\n",
        "- You can end this session using the input `/bye`": "- 您可以使用输入 `/bye` 结束此会话",
        "- The following code checks whether the ollama session is running correctly before proceeding to use ollama to evaluate the test set responses we generated in the previous section": "- 下面的代码在继续使用 ollama 评估我们在上一节中生成的测试集响应之前，检查 ollama 会话是否正常运行",
        "- Now, an alternative way to the `ollama run` command we used earlier to interact with the model is via its REST API in Python via the following function\n": "- 现在，我们之前用于与模型交互的 `ollama run` 命令的另一种替代方法是通过其 REST API 在 Python 中通过以下函数进行交互\n",
        "- Before you run the next cells in this notebook, make sure that ollama is still running (the previous code cells should print `\"Ollama running: True\"`)\n": "- 在运行本笔记本中的下一个单元格之前，请确保 ollama 仍在运行（前面的代码单元格应打印 `\"Ollama running: True\"`）\n",
        "- Next, run the following code cell to query the model": "- 接下来，运行以下代码单元格以查询模型",
        "- Note that if you are getting an `HTTPError: 404 Client Error: Not Found for url: http://localhost:11434/api/chat` error, this could mean you haven't downloaded the `llama3` model yet (to download the model, either use the UI or `ollama run llama3` on the terminal)": "- 请注意，如果您收到 `HTTPError: 404 Client Error: Not Found for url: http://localhost:11434/api/chat` 错误，这可能意味着您尚未下载 `llama3` 模型（要下载模型，请使用 UI 或在终端上使用 `ollama run llama3`）",
        "- Now, using the `query_model` function we defined above, we can evaluate the responses of our finetuned model; let's try it out on the first 3 test set responses we looked at in a previous section": "- 现在，使用我们在上面定义的 `query_model` 函数，我们可以评估微调模型的响应；让我们在上一节中看到的测试集的前 3 个响应上试用一下",
        "**Note: Better evaluation prompt**\n": "**注意：更好的评估提示**\n",
        "- [A reader (Ayoosh Kathuria) suggested](https://github.com/rasbt/LLMs-from-scratch/discussions/449) a longer, improved prompt that evaluates responses on a scale of 1–5 (instead of 1 to 100) and employs a grading rubric, resulting in more accurate and less noisy evaluations:\n": "- [一位读者 (Ayoosh Kathuria) 建议](https://github.com/rasbt/LLMs-from-scratch/discussions/449) 使用更长、改进的提示，在 1-5 的范围内评估响应（而不是 1 到 100），并采用评分标准，从而产生更准确和更少噪音的评估：\n",
        "- For more context and information, see [this](https://github.com/rasbt/LLMs-from-scratch/discussions/449) GitHub discussion\n": "- 有关更多背景信息和信息，请参阅 [此](https://github.com/rasbt/LLMs-from-scratch/discussions/449) GitHub 讨论\n",
        "- As we can see, the Llama 3 model provides a reasonable evaluation and also gives partial points if a model is not entirely correct, as we can see based on the \"cumulus cloud\" answer\n": "- 我们可以看到，Llama 3 模型提供了合理的评估，并且如果模型不完全正确，也会给出部分分数，正如我们根据“积云 (cumulus cloud)”答案所看到的那样\n",
        "- Note that the previous prompt returns very verbose evaluations; we can tweak the prompt to generate integer responses in the range between 0 and 100 (where 100 is best) to calculate an average score for our model\n": "- 请注意，之前的提示返回非常冗长的评估；我们可以调整提示以生成 0 到 100 范围内的整数响应（其中 100 为最佳），以计算模型的平均分数\n",
        "- The evaluation of the 110 entries in the test set takes about 1 minute on an M3 MacBook Air laptop": "- 测试集中 110 个条目的评估在 M3 MacBook Air 笔记本电脑上大约需要 1 分钟",
        "- Our model achieves an average score of above 50, which we can use as a reference point to compare the model to other models or to try out other training settings that may improve the model\n": "- 我们的模型达到了 50 分以上的平均分，我们可以将其作为参考点，将该模型与其他模型进行比较，或者尝试可能改进模型的其他训练设置\n",
        "- Note that ollama is not fully deterministic across operating systems (as of this writing), so the numbers you are getting might slightly differ from the ones shown above": "- 请注意，ollama 在不同的操作系统上并不是完全确定性的（在撰写本文时），因此您获得的数字可能与上面显示的数字略有不同",
        "- For reference, the original\n": "- 供参考，原始的\n",
        "  - Llama 3 8B base model achieves a score of 58.51\n": "  - Llama 3 8B 基础模型得分 58.51\n",
        "  - Llama 3 8B instruct model achieves a score of 82.65": "  - Llama 3 8B 指令模型得分 82.65",
        "## 7.9 Conclusions": "## 7.9 结论",
        "### 7.9.1 What's next\n": "### 7.9.1 下一步是什么\n",
        "- This marks the final chapter of this book\n": "- 这标志着本书的最后一章\n",
        "- We covered the major steps of the LLM development cycle: implementing an LLM architecture, pretraining an LLM, and finetuning it\n": "- 我们涵盖了 LLM 开发周期的主要步骤：实现 LLM 架构、预训练 LLM 和微调 LLM\n",
        "- An optional step that is sometimes followed after instruction finetuning, as described in this chapter, is preference finetuning\n": "- 如本章所述，指令微调之后有时会进行一个可选步骤，即偏好微调\n",
        "- Preference finetuning process can be particularly useful for customizing a model to better align with specific user preferences; see the [../04_preference-tuning-with-dpo](../04_preference-tuning-with-dpo) folder if you are interested in this\n": "- 偏好微调过程对于定制模型以更好地符合特定用户偏好特别有用；如果您对此感兴趣，请参阅 [../04_preference-tuning-with-dpo](../04_preference-tuning-with-dpo) 文件夹\n",
        "- This GitHub repository also contains a large selection of additional bonus material you may enjoy; for more information, please see the [Bonus Material](https://github.com/rasbt/LLMs-from-scratch?tab=readme-ov-file#bonus-material) section on this repository's README page": "- 此 GitHub 仓库还包含大量您可能会喜欢的额外奖励材料；有关更多信息，请参阅此仓库 README 页面上的 [奖励材料](https://github.com/rasbt/LLMs-from-scratch?tab=readme-ov-file#bonus-material) 部分",
        "### 7.9.2 Staying up to date in a fast-moving field\n": "### 7.9.2 在快速发展的领域中保持更新\n",
        "- No code in this section": "- 本节没有代码",
        "### 7.9.3 Final words\n": "### 7.9.3 结语\n",
        "- I hope you enjoyed this journey of implementing an LLM from the ground up and coding the pretraining and finetuning functions\n": "- 我希望您喜欢这个从头开始实现 LLM 并编写预训练和微调函数的旅程\n",
        "- In my opinion, implementing an LLM from scratch is the best way to understand how LLMs work; I hope you gained a better understanding through this approach\n": "- 在我看来，从头开始实现 LLM 是了解 LLM 工作原理的最佳方式；我希望您通过这种方法获得了更好的理解\n",
        "- While this book serves educational purposes, you may be interested in using different and more powerful LLMs for real-world applications\n": "- 虽然本书旨在用于教育目的，但您可能有兴趣在实际应用中使用不同且功能更强大的 LLM\n",
        "  - For this, you may consider popular tools such as axolotl ([https://github.com/OpenAccess-AI-Collective/axolotl](https://github.com/OpenAccess-AI-Collective/axolotl)) or LitGPT ([https://github.com/Lightning-AI/litgpt](https://github.com/Lightning-AI/litgpt)), which I help developing": "  - 为此，您可以考虑流行的工具，例如 axolotl ([https://github.com/OpenAccess-AI-Collective/axolotl](https://github.com/OpenAccess-AI-Collective/axolotl)) 或 LitGPT ([https://github.com/Lightning-AI/litgpt](https://github.com/Lightning-AI/litgpt))，我参与了它们的开发",
        "## Summary and takeaways\n": "## 总结和要点\n",
        "- See the [./gpt_instruction_finetuning.py](./gpt_instruction_finetuning.py) script, a self-contained script for instruction finetuning\n": "- 请参阅 [./gpt_instruction_finetuning.py](./gpt_instruction_finetuning.py) 脚本，这是一个用于指令微调的自包含脚本\n",
        "- [./ollama_evaluate.py](./ollama_evaluate.py) is a standalone script based on section 7.8 that evaluates a JSON file containing \"output\" and \"response\" keys via Ollama and Llama 3\n": "- [./ollama_evaluate.py](./ollama_evaluate.py) 是一个基于第 7.8 节的独立脚本，它通过 Ollama 和 Llama 3 评估包含“output”和“response”键的 JSON 文件\n",
        "- The [./load-finetuned-model.ipynb](./load-finetuned-model.ipynb) notebook illustrates how to load the finetuned model in a new session\n": "- [./load-finetuned-model.ipynb](./load-finetuned-model.ipynb) 笔记本说明了如何在将会话中加载微调后的模型\n",
        "- You can find the exercise solutions in [./exercise-solutions.ipynb](./exercise-solutions.ipynb)": "- 您可以在 [./exercise-solutions.ipynb](./exercise-solutions.ipynb) 中找到练习解答",
        "## What's next?\n": "## 下一步是什么？\n",
        "- Congrats on completing the book; in case you are looking for additional resources, I added several bonus sections to this GitHub repository that you might find interesting\n": "- 恭喜您读完本书；如果您正在寻找其他资源，我在此 GitHub 仓库中添加了几个您可能会感兴趣的奖励部分\n",
        "- The complete list of bonus materials can be viewed in the main README's [Bonus Material](https://github.com/rasbt/LLMs-from-scratch?tab=readme-ov-file#bonus-material) section\n": "- 奖励材料的完整列表可以在主 README 的 [奖励材料](https://github.com/rasbt/LLMs-from-scratch?tab=readme-ov-file#bonus-material) 部分查看\n",
        "- To highlight a few of my favorites:\n": "- 重点介绍几个我最喜欢的：\n",
        "  1. [Direct Preference Optimization (DPO) for LLM Alignment (From Scratch)](../04_preference-tuning-with-dpo/dpo-from-scratch.ipynb) implements a popular preference tuning mechanism to align the model from this chapter more closely with human preferences\n": "  1. [LLM 对齐的直接偏好优化 (DPO)（从头开始）](../04_preference-tuning-with-dpo/dpo-from-scratch.ipynb) 实现了一种流行的偏好调整机制，使本章中的模型更符合人类偏好\n",
        "  2. [Llama 3.2 From Scratch (A Standalone Notebook)](../../ch05/07_gpt_to_llama/standalone-llama32.ipynb), a from-scratch implementation of Meta AI's popular Llama 3.2, including loading the official pretrained weights; if you are up to some additional experiments, you can replace the `GPTModel` model in each of the chapters with the `Llama3Model` class (it should work as a 1:1 replacement)\n": "  2. [从头开始的 Llama 3.2（独立笔记本）](../../ch05/07_gpt_to_llama/standalone-llama32.ipynb)，这是 Meta AI 流行的 Llama 3.2 的从头开始实现，包括加载官方预训练权重；如果您想进行一些额外的实验，可以将每章中的 `GPTModel` 模型替换为 `Llama3Model` 类（它应该可以作为 1:1 的替换）\n",
        "  3. [Converting GPT to Llama](../../ch05/07_gpt_to_llama) contains code with step-by-step guides that explain the differences between GPT-2 and the various Llama models\n": "  3. [将 GPT 转换为 Llama](../../ch05/07_gpt_to_llama) 包含带有分步指南的代码，解释了 GPT-2 与各种 Llama 模型之间的差异\n",
        "  4. [Understanding the Difference Between Embedding Layers and Linear Layers](../../ch02/03_bonus_embedding-vs-matmul/embeddings-and-linear-layers.ipynb) is a conceptual explanation illustrating that the `Embedding` layer in PyTorch, which we use at the input stage of an LLM, is mathematically equivalent to a linear layer applied to one-hot encoded data\n": "  4. [理解嵌入层和线性层之间的区别](../../ch02/03_bonus_embedding-vs-matmul/embeddings-and-linear-layers.ipynb) 是一个概念性解释，说明了我们在 LLM 输入阶段使用的 PyTorch 中的 `Embedding` 层在数学上等同于应用于单热编码数据的线性层\n",
        "- Happy further reading!": "- 祝您阅读愉快！"
    }

    for cell in notebook['cells']:
        if cell['cell_type'] == 'markdown':
            for i, line in enumerate(cell['source']):
                if line in translations:
                    cell['source'][i] = translations[line]

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, ensure_ascii=False, indent=1)

if __name__ == "__main__":
    translate_notebook(
        '/Users/richard/Git/LLMs-from-scratch/ch07/01_main-chapter-code/ch07.ipynb',
        '/Users/richard/Git/LLMs-from-scratch/ch07/01_main-chapter-code/ch07_zh.ipynb'
    )
