
# -*- coding: utf-8 -*-
import json
import os

def translate_notebook(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        notebook = json.load(f)

    translations = {
        "# Direct Preference Optimization (DPO) for LLM Alignment (From Scratch)": "# 用于 LLM 对齐的直接偏好优化 (DPO) (从零开始)",
        "- This code notebook implements Direct Preference Optimization (DPO) from scratch and applies it to a large language model (LLM) to enhance its ability to generate responses that align more closely with user preferences": "- 本代码笔记本从零开始实现了直接偏好优化 (DPO)，并将其应用于大型语言模型 (LLM)，以增强其生成更符合用户偏好回复的能力。",
        "# 1) A brief introduction to DPO": "# 1) DPO 简介",
        "- DPO, proposed in the paper [Direct Preference Optimization: Your Language Model is Secretly a Reward Model](https://arxiv.org/abs/2305.18290), is an alternative to reinforcement learning from human feedback (RLHF) used in finetuning large language models (LLMs)\n": "- DPO，在论文 [Direct Preference Optimization: Your Language Model is Secretly a Reward Model](https://arxiv.org/abs/2305.18290) 中提出，是用于微调大型语言模型 (LLM) 的人类反馈强化学习 (RLHF) 的一种替代方案。\n",
        "- DPO can be used to finetune (or align) the model to generate responses that better align with user expectations and instructions\n": "- DPO 可用于微调（或对齐）模型，以生成更符合用户期望和指令的回复。\n",
        "- In instruction finetuning, we train the LLM to generate correct answers given a prompt\n": "- 在指令微调中，我们训练 LLM 在给定提示的情况下生成正确的答案。\n",
        "- However, in practice, there are multiple ways to give a correct answer, and correct answers can differ in style; for example, consider a technical and a more user-friendly response when asking an LLM to give recommendations when buying a laptop, as shown in the figure below\n": "- 然而，在实践中，给出正确答案的方式有多种，而且正确答案的风格可能不同；例如，如下图所示，当要求 LLM 给出购买笔记本电脑的建议时，考虑一个技术性的回复和一个更用户友好的回复。\n",
        "- RLHF and DPO are methods that can be used to teach the LLM to prefer one answer style over the other, that is, aligning better with user preferences\n": "- RLHF 和 DPO 是可用于教导 LLM 偏好一种答案风格而非另一种的方法，即更好地与用户偏好对齐。\n",
        "- The RLHF process, which requires training a separate reward model, is outlined below\n": "- RLHF 过程需要训练一个单独的奖励模型，概述如下。\n",
        "- Compared to RLHF, DPO aims to simplify the process by optimizing models directly for user preferences without the need for complex reward modeling and policy optimization\n": "- 与 RLHF 相比，DPO 旨在通过直接针对用户偏好优化模型来简化流程，而无需复杂的奖励建模和策略优化。\n",
        "- In other words, DPO focuses on directly optimizing the model's output to align with human preferences or specific objectives\n": "- 换句话说，DPO 专注于直接优化模型的输出，以符合人类偏好或特定目标。\n",
        "- Shown below is the main idea as an overview of how DPO works\n": "- 下图展示了 DPO 工作原理的主要思想概览。\n",
        "- The concrete equation to implement the DPO loss is shown below; we will revisit the equation when we implement it in Python further down in this code notebook\n": "- 实现 DPO 损失的具体方程如下所示；我们将在本笔记本后面用 Python 实现它时再次回顾该方程。\n",
        "- In the equation above,\n": "- 在上面的方程中，\n",
        "  - \"expected value\" $\\mathbb{E}$ is statistics jargon and stands for the average or mean value of the random variable (the expression inside the brackets); optimizing $-\\mathbb{E}$ aligns the model better with user preferences\n": "  - “期望值” $\\mathbb{E}$ 是统计术语，代表随机变量（括号内的表达式）的平均值或均值；优化 $-\\mathbb{E}$ 使模型更好地与用户偏好对齐。\n",
        "  - The $\\pi_{\\theta}$ variable is the so-called policy (a term borrowed from reinforcement learning) and represents the LLM we want to optimize; $\\pi_{ref}$ is a reference LLM, which is typically the original LLM before optimization (at the beginning of the training, $\\pi_{\\theta}$ and $\\pi_{ref}$ are typically the same)\n": "  - $\\pi_{\\theta}$ 变量是所谓的策略（借用自强化学习的术语），代表我们想要优化的 LLM；$\\pi_{ref}$ 是参考 LLM，通常是优化前的原始 LLM（在训练开始时，$\\pi_{\\theta}$ 和 $\\pi_{ref}$ 通常是相同的）。\n",
        "  - $\\beta$ is a hyperparameter to control the divergence between the $\\pi_{\\theta}$ and the reference model; increasing $\\beta$ reduces the impact of the difference between\n": "  - $\\beta$ 是一个超参数，用于控制 $\\pi_{\\theta}$ 和参考模型之间的散度；增加 $\\beta$ 会减少两者之间差异的影响。\n",
        "$\\pi_{\\theta}$ and $\\pi_{ref}$ in terms of their log probabilities on the overall loss function, thereby decreasing the divergence between the two models\n": "$\\pi_{\\theta}$ 和 $\\pi_{ref}$ 在总损失函数上的对数概率方面，从而减少两个模型之间的散度。\n",
        "  - the logistic sigmoid function, $\\sigma(\\centerdot)$ transforms the log-odds of the preferred and rejected responses (the terms inside the logistic sigmoid function) into a probability score \n": "  - logistic sigmoid 函数 $\\sigma(\\centerdot)$ 将偏好和拒绝回复的对数几率（logistic sigmoid 函数内的项）转换为概率分数。\n",
        "- To avoid bloating the code notebook with a more detailed discussion, I may write a separate standalone article with more details on these concepts in the future\n": "- 为了避免代码笔记本过于臃肿，我将来可能会写一篇单独的文章，详细讨论这些概念。\n",
        "- In the meantime, if you are interested in comparing RLHF and DPO, please see the section [2.2. RLHF vs Direct Preference Optimization (DPO)](https://magazine.sebastianraschka.com/i/142924793/rlhf-vs-direct-preference-optimization-dpo) in my article [Tips for LLM Pretraining and Evaluating Reward Models](https://magazine.sebastianraschka.com/p/tips-for-llm-pretraining-and-evaluating-rms)": "- 同时，如果您有兴趣比较 RLHF 和 DPO，请参阅我的文章 [Tips for LLM Pretraining and Evaluating Reward Models](https://magazine.sebastianraschka.com/p/tips-for-llm-pretraining-and-evaluating-rms) 中的 [2.2. RLHF vs Direct Preference Optimization (DPO)](https://magazine.sebastianraschka.com/i/142924793/rlhf-vs-direct-preference-optimization-dpo) 部分。",
        "# 2) Preparing a preference dataset for DPO": "# 2) 准备 DPO 的偏好数据集",
        "- Let's begin by loading and preparing the dataset, which may already answer a lot of the questions you might have before we revisit the DPO loss equation\n": "- 让我们开始加载和准备数据集，这可能会在我们重新审视 DPO 损失方程之前回答您的许多问题。\n",
        "- Here, we work with a dataset that contains more polite and less polite responses to instruction prompts (concrete examples are shown in the next section)\n": "- 这里，我们使用一个包含对指令提示的更礼貌和不太礼貌回复的数据集（具体示例将在下一节中展示）。\n",
        "- The dataset was generated via the [create-preference-data-ollama.ipynb](create-preference-data-ollama.ipynb) notebook": "- 该数据集是通过 [create-preference-data-ollama.ipynb](create-preference-data-ollama.ipynb) 笔记本生成的。",
        "## 2.1) Loading a preference dataset": "## 2.1) 加载偏好数据集",
        "- The dataset is a json file with 1100 entries:": "- 该数据集是一个包含 1100 个条目的 json 文件：",
        "- Let's take a look at two example entries:": "- 让我们看两个示例条目：",
        "- As we can see above, the dataset consists of 5 keys:\n": "- 如上所示，数据集包含 5 个键：\n",
        "    - The `'instruction'` and `'input'` that are used as LLM inputs\n": "    - 用作 LLM 输入的 `'instruction'` 和 `'input'`\n",
        "    - The `'output'` contains the response the model was trained on via the instruction finetuning step in chapter 7\n": "    - `'output'` 包含模型在第 7 章中通过指令微调步骤训练的回复\n",
        "    - the `'chosen'` and `'rejected'` entries are the entries we use for DPO; here `'chosen'` is the preferred response, and `'rejected'` is the dispreferred response\n": "    - `'chosen'` 和 `'rejected'` 条目是我们用于 DPO 的条目；这里 `'chosen'` 是首选回复，`'rejected'` 是非首选回复\n",
        "- The goal is to get the model to follow the style of the chosen over the rejected responses": "- 目标是让模型遵循首选回复的风格，而不是被拒绝回复的风格",
        "- Below is a utility function that formats the model input by applying the Alpaca prompt style similar to chapter 7 ([../01_main-chapter-code/ch07.ipynb](../01_main-chapter-code/ch07.ipynb)):\n": "- 下面是一个实用函数，它通过应用类似于第 7 章 ([../01_main-chapter-code/ch07.ipynb](../01_main-chapter-code/ch07.ipynb)) 的 Alpaca 提示风格来格式化模型输入：\n",
        "- Similarly, we can format the chosen and rejected responses using the Alpaca prompt style:": "- 同样，我们可以使用 Alpaca 提示风格格式化首选和被拒绝的回复：",
        "## 2.2) Creating training, validation, and test splits": "## 2.2) 创建训练、验证和测试集",
        "- Next, we divide the dataset into 3 subsets, 85% training data, 5% validation data, and 10% test data:": "- 接下来，我们将数据集分为 3 个子集，85% 的训练数据，5% 的验证数据和 10% 的测试数据：",
        "## 2.3) Developing a `PreferenceDataset` class and batch processing function": "## 2.3) 开发 `PreferenceDataset` 类和批处理函数",
        "- In this section, we rewrite the `InstructionDataset` class from chapter 7 ([../01_main-chapter-code/ch07.ipynb](../01_main-chapter-code/ch07.ipynb)) for DPO\n": "- 在本节中，我们重写第 7 章 ([../01_main-chapter-code/ch07.ipynb](../01_main-chapter-code/ch07.ipynb)) 中的 `InstructionDataset` 类以用于 DPO。\n",
        "- This means that instead of focusing on single output sequences (responses), we modify the dataset class to return pairs of responses where one is preferred (\"chosen\") over the other (\"rejected\")\n": "- 这意味着我们要修改数据集类，使其返回一对回复，其中一个是首选（“chosen”），另一个是非首选（“rejected”），而不是专注于单个输出序列（回复）。\n",
        "- Overall, the `PreferenceDataset` is almost identical to the `InstructionDataset` used in chapter 7:": "- 总的来说，`PreferenceDataset` 与第 7 章中使用的 `InstructionDataset` 几乎相同：",
        "- Along with an updated `PreferenceDataset` class, we also need an updated batch collation function that we use to pad the sequences in each batch to an equal length so that we can assemble them in batches\n": "- 除了更新的 `PreferenceDataset` 类，我们还需要一个更新的批处理整理函数，用于将每批中的序列填充到相同的长度，以便我们可以分批组装它们。\n",
        "- I added comments to the code below to illustrate the process; however, it might be easiest to understand how it works by looking at the example inputs and outputs further below:": "- 我在下面的代码中添加了注释来说明这个过程；然而，通过查看下面的示例输入和输出可能最容易理解它是如何工作的：",
        "- Before we start using the custom collate function, let's make version of it with some of its function arguments prefilled:": "- 在开始使用自定义整理函数之前，让我们创建一个预先填充了一些函数参数的版本：",
        "- Now, let's see the `customized_collate_fn` in action and apply it to some sample data from our preference dataset; for this, we take the first two entries:": "- 现在，让我们看看 `customized_collate_fn` 的实际效果，并将其应用于我们的偏好数据集中的一些样本数据；为此，我们取前两个条目：",
        "- Next, let's instantiate an `example_dataset` and use a PyTorch `DataLoader` to create an `example_dataloader` that mimics the data loader we will use for the model training later:": "- 接下来，让我们实例化一个 `example_dataset` 并使用 PyTorch `DataLoader` 创建一个 `example_dataloader`，它模仿我们稍后用于模型训练的数据加载器：",
        "- The dataset has the following keys:": "- 数据集具有以下键：",
        "- The prompts are a list of tensors, where each tensor contains the token IDs for a given example; since we selected a batch size of 2, we have two lists of token ID tensors here:": "- 提示是一个张量列表，其中每个张量包含给定示例的 token ID；因为我们选择了批量大小为 2，所以这里有两个 token ID 张量列表：",
        "- We don't really need the responses for training; what we need to feed to the model during training are the `\"chosen\"` and `\"rejected\"` entries\n": "- 我们实际上不需要回复来进行训练；在训练期间我们需要提供给模型的是 `\"chosen\"` 和 `\"rejected\"` 条目。\n",
        "- The  `\"chosen\"` and `\"rejected\"` response entries are padded so that we can stack them as tensors; similar to the prompts, these response texts are encoded into token IDs:": "- `\"chosen\"` 和 `\"rejected\"` 回复条目被填充，以便我们可以将它们堆叠为张量；与提示类似，这些回复文本被编码为 token ID：",
        "- The token IDs above represent the model inputs, but in this format, they are hard to interpret for us humans\n": "- 上面的 token ID 代表模型输入，但这种格式对我们人类来说很难解释。\n",
        "- So, let's implement a small utility function to convert them back into text so that we can inspect and interpret them more easily:": "- 因此，让我们实现一个小实用函数，将它们转换回文本，以便我们可以更轻松地检查和解释它们：",
        "- Let's apply the `decode_tokens_from_batch` utility function to the first prompt entry in the batch:": "- 让我们将 `decode_tokens_from_batch` 实用函数应用于批次中的第一个提示条目：",
        "- As we can see above, the prompt was correctly formatted; let's now do the same for the `\"chosen\"` response:": "- 如上所示，提示已正确格式化；现在让我们对 `\"chosen\"` 回复做同样的事情：",
        "- As we can see above, similar to instruction finetuning, the response that is passed to the model during training also contains the input prompt\n": "- 如上所示，类似于指令微调，在训练期间传递给模型的回复也包含输入提示。\n",
        "- Also note that we included `<|endoftext|>` tokens as padding tokens, which are necessary so that we can extend the responses to a similar length to stack them as a batch\n": "- 另外请注意，我们包含了 `<|endoftext|>` token 作为填充 token，这是必要的，以便我们可以将回复扩展到相似的长度以将其堆叠为一批。\n",
        "- Don't worry; the `<|endoftext|>` tokens will be ignored in the loss later so that they won't affect the training outcome\n": "- 别担心；`<|endoftext|>` token 稍后将在损失中被忽略，因此它们不会影响训练结果。\n",
        "- Let's now also inspect the corresponding rejected response:": "- 现在让我们也检查相应的被拒绝的回复：",
        "- In this case, as we can see above, the rejected response is a more impolite version of the chosen response (we don't want the model to generate impolite responses)\n": "- 在这种情况下，如上所示，被拒绝的回复是首选回复的更不礼貌版本（我们不希望模型生成不礼貌的回复）。\n",
        "- Lastly, let's talk about the data masks: if you took a closer look at our custom collate function we implemented above, we created a `\"chosen_mask\"` and a `\"rejected_mask\"` for each dataset entry\n": "- 最后，让我们谈谈数据掩码：如果您仔细查看我们上面实现的自定义整理函数，我们为每个数据集条目创建了一个 `\"chosen_mask\"` 和一个 `\"rejected_mask\"`。\n",
        "- The masks have the same shape as the response entries, as shown below for the `\"chosen\"` entry:": "- 掩码具有与回复条目相同的形状，如下所示的 `\"chosen\"` 条目：",
        "- The contents of these masks are boolean (`True` and `False`) values:": "- 这些掩码的内容是布尔值（`True` 和 `False`）：",
        "- The `True` values denote token IDs that correspond to the actual response\n": "- `True` 值表示对应于实际回复的 token ID。\n",
        "- the `False` tokens correspond to token IDs that correspond to either prompt tokens (if we set `mask_prompt_tokens=True` in the `customized_collate_fn` function, which we previously did) or padding tokens\n": "- `False` token 对应于提示 token（如果我们在 `customized_collate_fn` 函数中设置了 `mask_prompt_tokens=True`，我们之前已经这样做了）或填充 token 的 token ID。\n",
        "- Hence, we can use the mask as a selection mask to select only the token IDs that correspond to the response, that is, stripping all prompt and padding tokens, as we can see below:": "- 因此，我们可以使用掩码作为选择掩码，仅选择对应于回复的 token ID，即去除所有提示和填充 token，如下所示：",
        "- We will make use of this mask to ignore prompt and padding tokens when computing the DPO loss later": "- 我们稍后在计算 DPO 损失时将利用此掩码来忽略提示和填充 token",
        "## 2.4 Creating training, validation, and test set data loaders": "## 2.4 创建训练、验证和测试集数据加载器",
        "- Above, we worked with a small example subsets from the preference dataset for illustration purposes\n": "- 上面，为了说明目的，我们使用了偏好数据集中的一个小示例子集。\n",
        "- Let's now create the actual training, validation, and test set data loaders\n": "- 现在让我们创建实际的训练、验证和测试集数据加载器。\n",
        "- This process is identical to creating the data loaders in the pretraining and instruction finetuning chapters and thus should be self-explanatory": "- 这个过程与预训练和指令微调章节中创建数据加载器的过程完全相同，因此应该是不言自明的。",
        "- Let's iterate through the data loader and take a look at the dataset shapes:": "- 让我们遍历数据加载器并查看数据集形状：",
        "- Each row shows the shape of the `\"chosen\"` and `\"rejected\"` entries in each batch\n": "- 每一行显示每批中 `\"chosen\"` 和 `\"rejected\"` 条目的形状。\n",
        "- Since we applied padding on a batch-by-batch basis, each row has a different shape\n": "- 由于我们是在逐批的基础上应用填充，因此每一行都有不同的形状。\n",
        "- This is for efficiency reasons because it would be inefficient to pad all samples to the longest sample in the whole dataset": "- 这是出于效率原因，因为将所有样本填充到整个数据集中最长样本的长度将是低效的。",
        "# 3) Loading a finetuned LLM for DPO alignment": "# 3) 加载用于 DPO 对齐的微调 LLM",
        "- LLM alignment steps, such as RLHF or DPO, assume that we already have an instruction-finetuned model\n": "- LLM 对齐步骤（如 RLHF 或 DPO）假设我们已经有一个经过指令微调的模型。\n",
        "- This section contains minimal code to load the model that was instruction finetuned and saved in chapter 7 (via [../01_main-chapter-code/ch07.ipynb](../01_main-chapter-code/ch07.ipynb))\n": "- 本节包含最少的代码来加载在第 7 章中微调并保存的模型（通过 [../01_main-chapter-code/ch07.ipynb](../01_main-chapter-code/ch07.ipynb)）。\n",
        "- Make sure you run the chapter 7 code first to create the instruction-finetuned model before you proceed\n": "- 在继续之前，请确保先运行第 7 章的代码以创建指令微调模型。\n",
        "- The code below will copy the instruction-finetuned model into the current directory:": "- 下面的代码将把指令微调的模型复制到当前目录：",
        "- Next, we reuse the basic configuration from previous chapters to load the model weights:": "- 接下来，我们重用前几章的基本配置来加载模型权重：",
        "- Before training the loaded model with DPO, let's make sure that the finetuned model was saved and loaded correctly by trying it out on some sample data:": "- 在使用 DPO 训练加载的模型之前，让我们通过在一些样本数据上进行试用来确保微调模型已正确保存和加载：",
        "- As we can see above, the model gives a reasonable and correct response\n": "- 如上所示，模型给出了合理且正确的回复。\n",
        "- As explained in chapter 7, in practice, we would clean up the response to only return the response text with the prompt and prompt style removed (similar to what you are familiar with from ChatGPT, for example):": "- 正如第 7 章中所解释的，在实践中，我们会清理回复，只返回去除了提示和提示风格的回复文本（例如，类似于您熟悉的 ChatGPT）：",
        "- Now, we are almost ready to get to the DPO part\n": "- 现在，我们几乎准备好进入 DPO 部分了。\n",
        "- As mentioned at the beginning of this notebook, DPO works with two LLMs: a policy model (the LLM that we want to optimize) and a reference model (the original model that we keep unchanged)\n": "- 正如本笔记本开头所提到的，DPO 使用两个 LLM：策略模型（我们要优化的 LLM）和参考模型（我们保持不变的原始模型）。\n",
        "- Below, we rename the `model` as `policy_model` and instantiate a second instance of the model we refer to as the `reference_model`": "- 下面，我们将 `model` 重命名为 `policy_model`，并实例化我们要称为 `reference_model` 的模型的第二个实例。",
        "# 4) Coding the DPO Loss Function": "# 4) 编写 DPO 损失函数",
        "- After we took care of the model loading and dataset preparation in the previous sections, we can now get to the fun part and code the DPO loss\n": "- 在前几节中完成了模型加载和数据集准备之后，我们现在可以进入有趣的部分并编写 DPO 损失代码。\n",
        "- Note that the DPO loss code below is based on the method proposed in the [Direct Preference Optimization: Your Language Model is Secretly a Reward Model](https://arxiv.org/abs/2305.18290) paper\n": "- 请注意，下面的 DPO 损失代码基于 [Direct Preference Optimization: Your Language Model is Secretly a Reward Model](https://arxiv.org/abs/2305.18290) 论文中提出的方法。\n",
        "- For reference, the core DPO equation is shown again below:\n": "- 供参考，核心 DPO 方程再次显示如下：\n",
        "- In code, we can implement the DPO loss as follows:": "- 在代码中，我们可以按如下方式实现 DPO 损失：",
        "- If you are familiar with logarithms, note that we have the general relationship $\\log\\left(\\frac{a}{b}\\right) = \\log a - \\log b$, which we applied in the code above\n": "- 如果您熟悉对数，请注意我们有一般关系 $\\log\\left(\\frac{a}{b}\\right) = \\log a - \\log b$，我们在上面的代码中应用了它。\n",
        "- Keeping this in mind, let's go through some of the steps (we will calculate the `logprobs` using a separate function later)\n": "- 记住这一点，让我们浏览一下其中的一些步骤（稍后我们将使用单独的函数计算 `logprobs`）。\n",
        "- Let's start with the lines\n": "- 让我们从以下几行开始\n",
        "- These lines above calculate the difference in log probabilities (logits) for the chosen and rejected samples for both the policy model and the reference model (this is due to $\\log\\left(\\frac{a}{b}\\right) = \\log a - \\log b$):\n": "- 上面的这些行计算了策略模型和参考模型的首选样本和拒绝样本的对数概率（logits）差异（这是由于 $\\log\\left(\\frac{a}{b}\\right) = \\log a - \\log b$）：\n",
        "- Next, the code `logits = model_logratios - reference_logratios` computes the difference between the model's log ratios and the reference model's log ratios, i.e., \n": "- 接下来，代码 `logits = model_logratios - reference_logratios` 计算模型的对数比率与参考模型的对数比率之间的差异，即\n",
        "- Finally, `losses = -F.logsigmoid(beta * logits)`  calculates the loss using the log-sigmoid function; in the original equation, the term inside the expectation is \n": "- 最后，`losses = -F.logsigmoid(beta * logits)` 使用 log-sigmoid 函数计算损失；在原始方程中，期望内的项是\n",
        "- Above, we assumed that the log probabilities were already computed; let's now define a `compute_logprobs` function that we can use to compute these log probabilities that were passed into the `compute_dpo_loss` function above, that is, the values $\\pi_\\theta (y_w \\mid x)$, ${\\pi_\\theta (y_l \\mid x)}$, and so forth:": "- 上面，我们假设对数概率已经计算出来了；现在让我们定义一个 `compute_logprobs` 函数，我们可以用它来计算传递给上面 `compute_dpo_loss` 函数的这些对数概率，即值 $\\pi_\\theta (y_w \\mid x)$，${\\pi_\\theta (y_l \\mid x)}$ 等等：",
        "- Note that this function above might look a bit intimidating at first due to the `torch.gather` function, but it's pretty similar to what happens under the hood in PyTorch's `cross_entropy` function\n": "- 请注意，上面的这个函数起初可能看起来有点令人生畏，因为有 `torch.gather` 函数，但它与 PyTorch 的 `cross_entropy` 函数在幕后发生的情况非常相似。\n",
        "- For example, consider the following example:": "- 例如，考虑以下示例：",
        "- So, above, we can see that the two implementations are equivalent, but let's narrow down a bit further to the `torch.gather` mechanics\n": "- 所以，上面我们可以看到这两种实现是等效的，但让我们进一步缩小到 `torch.gather` 机制。\n",
        "- Consider the following two tensors:": "- 考虑以下两个张量：",
        "- Above, `t` is a tensor we want to select from, and `m` is a mask to specify how we want to select\n": "- 上面，`t` 是我们要从中选择的张量，`m` 是指定我们如何选择的掩码。\n",
        " - For instance, since `m` contains `[1, 1]` n the first row, it will select two times the value of `t` in index position `1`, which is the value 2.\n": " - 例如，因为 `m` 在第一行包含 `[1, 1]`，它将选择索引位置 `1` 处的 `t` 值的两倍，即值 2。\n",
        " - The second row of `m`, `[0, 1]`, selects index positions 0 and 1 in the second row or `t`, which are `3.` and `4.`": " - `m` 的第二行 `[0, 1]` 选择第二行或 `t` 中的索引位置 0 和 1，即 `3.` 和 `4.`",
        "- In other words, `torch.gather` is a selection function\n": "- 换句话说，`torch.gather` 是一个选择函数。\n",
        "- When we computed the loss earlier, we used it to retrieve the log probabilities corresponding to the correct token in the 50,257-token vocabulary\n": "- 当我们之前计算损失时，我们使用它来检索对应于 50,257 个 token 词汇表中正确 token 的对数概率。\n",
        "- The \"correct\" tokens are the tokens given in the response entry": "- “正确”的 token 是回复条目中给出的 token。",
        "- Regarding the `compute_logprobs` function above, we use `torch.gather` here because it gives us a bit more control than `cross_entropy`, but is, in essence, a similar idea\n": "- 关于上面的 `compute_logprobs` 函数，我们在这里使用 `torch.gather`，因为它比 `cross_entropy` 给了我们更多的控制权，但本质上是一个类似的想法。\n",
        "- The `selection_mask` we use there is to optionally ignore prompt and padding tokens\n": "- 我们在那里使用的 `selection_mask` 是为了可选择地忽略提示和填充 token。\n",
        "- We can then use the `compute_logprobs` function as follows to compute the inputs for the `compute_dpo_loss` loss function": "- 然后我们可以按如下方式使用 `compute_logprobs` 函数来计算 `compute_dpo_loss` 损失函数的输入：",
        "- The above function works for a single batch, for example:": "- 上面的函数适用于单个批次，例如：",
        "- Below, we extend this function to work for a specified `num_batches` in a data loader:": "- 下面，我们将扩展此函数以适用于数据加载器中指定的 `num_batches`：",
        "- Why a specified `num_batches`? That's purely for efficiency reasons (because calculating the loss on the whole dataset each time would slow down the training significantly)": "- 为什么要指定 `num_batches`？这纯粹是出于效率原因（因为每次计算整个数据集的损失会显着降低训练速度）",
        "- Lastly, we define a convenience function for our training function later; this `evaluate_dpo_loss_loader` function computes the DPO loss and rewards for both the training and validation loader for logging purposes:": "- 最后，我们稍后为我们的训练函数定义一个便利函数；此 `evaluate_dpo_loss_loader` 函数计算训练和验证加载器的 DPO 损失和奖励，以便进行记录：",
        "- In this section, we covered a lot of ground as a brief recap:\n": "- 在本节中，我们涵盖了很多内容，简要回顾一下：\n",
        "  - The flow is: compute `logits` via the models $\\rightarrow$ `compute_logprobs` from logits $\\rightarrow$ compute `compute_dpo_loss` from log probabilities\n": "  - 流程是：通过模型计算 `logits` $\\rightarrow$ 从 logits 计算 `compute_logprobs` $\\rightarrow$ 从对数概率计算 `compute_dpo_loss`\n",
        "  - we have the `compute_dpo_loss_batch` function that facilitates the process above\n": "  - 我们有 `compute_dpo_loss_batch` 函数来促进上述过程\n",
        "  - the `compute_dpo_loss_loader` utility function applies the `compute_dpo_loss_batch` function to a data loader\n": "  - `compute_dpo_loss_loader` 实用函数将 `compute_dpo_loss_batch` 函数应用于数据加载器\n",
        "  - the `evaluate_dpo_loss_loader` function applies the `compute_dpo_loss_batch` to both the training and validation set data loaders for logging purposes": "  - `evaluate_dpo_loss_loader` 函数将 `compute_dpo_loss_batch` 应用于训练和验证集数据加载器以进行记录",
        "# 5) Training the model": "# 5) 训练模型",
        "- After setting up the DPO loss functions in the previous section, we can now finally train the model\n": "- 在上一节设置好 DPO 损失函数后，我们现在终于可以训练模型了。\n",
        "- Note that this training function is the same one we used for pretraining and instruction finetuning, with minor differences:\n": "- 请注意，此训练函数与我们用于预训练和指令微调的函数相同，只有细微差别：\n",
        " - we swap the cross-entropy loss with our new DPO loss function\n": " - 我们将交叉熵损失替换为我们的新 DPO 损失函数\n",
        " - we also track the rewards and reward margins, which are commonly used in RLHF and DPO contexts to track the training progress\n": " - 我们还跟踪奖励和奖励差，这在 RLHF 和 DPO 环境中通常用于跟踪训练进度\n",
        "- Before we start the training, let's print the initial losses and rewards:": "- 在开始训练之前，让我们打印初始损失和奖励：",
        "- As we can see based on the tracked results above, the loss improves\n": "- 正如我们在上面跟踪的结果中所看到的，损失有所改善。\n",
        "- Also, the reward margins, which is the difference between the rewards of the chosen and the rejected responses, improve, which is a good sign\n": "- 此外，奖励差（即首选回复和被拒绝回复的奖励之差）也有所改善，这是一个好兆头。\n",
        "- Let's take a more concrete look at these results in the next section": "- 让我们在下一节中更具体地看看这些结果",
        "# 6) Analyzing the results": "# 6) 分析结果",
        "- Let's begin analyzing the results by plotting the DPO loss:": "- 让我们通过绘制 DPO 损失来开始分析结果：",
        "- As we can see above, the loss continues to improve, which is a good sign\n": "- 如上所示，损失持续改善，这是一个好兆头。\n",
        "- Based on the downward slope, one might be tempted to train the model a bit further (and readers are encouraged to try this), but note that DPO is prone to collapse, where the model may start generating nonsensical responses\n": "- 基于下降的斜率，人们可能会想进一步训练模型（鼓励读者尝试这样做），但请注意，DPO 容易崩溃，模型可能会开始生成荒谬的回复。\n",
        "- Next, let's take a look at the reward margins:": "- 接下来，让我们看看奖励差：",
        "- As we can see, and as it's desired, the reward margins improve; this mirrors the loss curve and is a good sign\n": "- 正如我们所看到的，这也是我们所希望的，奖励差有所改善；这反映了损失曲线，是一个好兆头。\n",
        "- Note that DPO losses and reward margins are valuable metrics to track during training; however, they don't tell the whole story\n": "- 请注意，DPO 损失和奖励差是训练期间跟踪的有价值的指标；然而，它们并不能说明全部情况。\n",
        "- Lastly, and most importantly, we have to conduct a qualitative check of the responses\n": "- 最后，也是最重要的是，我们必须对回复进行定性检查。\n",
        "- Here, we will look at the response (in addition, you could use an LLM to score the responses similar to chapter 7)": "- 在这里，我们将查看回复（此外，您可以使用类似于第 7 章的 LLM 对回复进行评分）",
        "- As we can see based on the reference model and policy model responses above, the optimized model (i.e., the policy model) indeed slightly changed its style compared to the original model (i.e., reference model)\n": "- 正如我们基于上面的参考模型和策略模型回复所看到的，优化后的模型（即策略模型）与原始模型（即参考模型）相比，确实稍微改变了它的风格。\n",
        "- For instance, `\"Dance\" can be classified as a verb.` changed to `The input string \"Dance\" could be classified as a verb.` which is a slightly more polite response (the use of \"could\" instead of \"can\" makes the statement sound less assertive and more tentative)": "- 例如，`\"Dance\" can be classified as a verb.` 变成了 `The input string \"Dance\" could be classified as a verb.`，这是一个稍微礼貌一点的回复（使用“could”而不是“can”使陈述听起来不那么武断，更具试探性）"
    }

    for cell in notebook['cells']:
        if cell['cell_type'] == 'markdown':
            new_source = []
            for line in cell['source']:
                translated_line = translations.get(line.strip(), line)
                # Keep original formatting if not translated, or apply translation
                if line.strip() in translations:
                     new_source.append(translated_line + ('\n' if line.endswith('\n') else ''))
                else:
                    new_source.append(line)
            cell['source'] = new_source

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, ensure_ascii=False, indent=1)

if __name__ == "__main__":
    translate_notebook('ch07/04_preference-tuning-with-dpo/dpo-from-scratch.ipynb', 'ch07/04_preference-tuning-with-dpo/dpo-from-scratch_zh.ipynb')
